### PR TITLE
Add various opportunities to strengthen the instance

### PR DESCRIPTION
**Pull request by cociweb**
Hello,

This PR adds the opportunity to strengthen the plain http connection. Additionally, into the apache config folder you can mount your own configuration.

Please take care for the healthcheck, which requires that http should be healthy also (option1: create and host on 2 virtualhost for 443 and 80; option2: host on 443 and redirect the http://localhost/lam with reverse proxy).  

Br,
cociweb

### CODE REVIEW

**Comment by gruberroland** [comment]
Are there big reasons to go for option 2 with proxy? If not then I would say ssl module should be enough.

**Comment by cociweb** [comment]
the reason is the redirect:
The [wget healthcheck](https://github.com/LDAPAccountManager/lam/blob/51d042b4a50534cbfae5e8bd4575c9622eafaa4e/lam-packaging/docker/Dockerfile#L114-L115) requires answer on http://localhost. It can be redirected via proxy (without virtualhosts). - Unfortunatelly, the rewrite module is not enough alone: it cannot redirect to another port/socket with the inbuilt apache variables. 
The other option (without the need of the reverse proxy) could be to make 2 parallel vhosts with the exactly the same records, except port/proto. With the current single apache.conf file it is not possible to create virtualhosts. (it is mounted into [apache2/conf-available](https://github.com/LDAPAccountManager/lam/blob/450b2f22c0560ffd6040a5c17cd7f28f6cb67a00/lam-packaging/debian/postinst#L77) instead of apache2/sites-available.) virtualhosts should be located in sites-enabed, otherwise it throw alarms, and not able to start apache. 
So reverse proxy could be an alternative, or we need to revise the location of the apache.conf file(s) binding to avoid the.
Actually, I've rebinded the whole apache config directory, and I not used the proxy module. Proxy gives flexibility (and security backdoors), and only need, if we stick to the current apache.conf file.

**Comment by gruberroland** [comment]
Which file exactly is the issue? There are no files in "sites-enabled". There is no virtual host defined by the image.
So you could simply mount some virtual host configurations to "sites-enabled", can't you?

The file "conf-enabled/laminit.conf" only contains the rewrite for the root URL. Is this an issue?

**Comment by cociweb** [comment]
Yes, that was the case how I got it working. Mount the full apache2 folder, because:
1: add 443 (+80) to port.conf (I've added in the following condition: `<Ifmodule mod_ssl.c/>` - I don't know what are the other ssl predefined modules used for....)
2: in sites-enabled put everything into a virtualhost:443, what the laminit.conf has. + additional ssl+certs
3: in sites-enabled put everything into a virtualhost:80 what the laminit.conf has (rewrite module should also work: but it not backward compatible: if only 80 is used by the users, so script is needed to be universal. As a gratis you can also use 
If you compare the two way from security pov:
Since you don't know how the user wouldreverseproxy to redirect to 443 :D)
4: remove the laminit.conf (ldap-account-manager.conf) from conf-enabled. (since conf-enabled is a global place of declaration, it should work, but multiple virtualhosts require their own documentroot+others. It was not worked with minimal virtualhost config.)
+(use the port constrain XXX:443 in docker)

if you have additionally proxy installed <more elegant way / more userfriendly from docker-compose PoV/requires less code modification>, only 'conf-enabled' is mounted:
1: not need to add 443 into port.conf. (ssl data will be force served over port 80, and it will drop html error if you use http:// instead of https://)
2: edit laminit (ldap-account-manager.conf) in conf-enabled: add the ssl+cert settings and redirect with proxy from http://localhost/lam to https://localhost:80/lam (the rewrite module not able to do it: apache serves the above mentioned html error than before the module take into consideration) 
3: no further filemagic
+(use the port constrain XXX:80 in docker)

Anyway, in my opinion, the first way (or it's variant) should be supported (by scripts: avoid the opening of unused ports), but the second is easier to implement by the user/guide. With the current PR both way is possible.
Additionally, I'm not an apache expert,  I've played a whole day with it with many trial&error. A cross-check/revision and/or additional scripts would be appreciated to be userproof.

**Comment by gruberroland** [comment]
Thanks a lot for the details. I will apply the changes and notify you here when it is done.

**Comment by gruberroland** [comment]
I moved the laminit to sites-enabled and activated the SSL module. The ports.conf was already fine.

Please check if you see any more issues: https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/Dockerfile

**Comment by gruberroland** [comment]
There is no predefined virtual host for SSL as this requires certificates. Needs to be done manually by mounting sites-enabled.

**Comment by gruberroland** [comment]
Changes are in latest Docker image

**Pull request closed without merging**
